# Generated by Django 3.0.7 on 2020-06-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200607_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='measurement_system',
            field=models.CharField(blank=True, choices=[('METRIC', 'METRIC'), ('IMPERIAL', 'IMPERIAL')], default='METRIC', max_length=8),
        ),
    ]
