# Generated by Django 3.0.7 on 2020-06-22 16:33

from django.db import migrations
import django_measurement.models
import measurement.measures.distance


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200608_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance),
        ),
    ]
