# Generated by Django 3.0.7 on 2020-07-10 17:00

from django.db import migrations
import django_measurement.models
import measurement.measures.distance


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200710_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True),
        ),
    ]
