# Generated by Django 3.0.7 on 2020-08-10 15:38

import cloudinary.models
import datetime
from django.db import migrations, models
import django_measurement.models
import measurement.measures.distance
import measurement.measures.mass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_measure', models.DateField(default=datetime.date.today)),
                ('front_image_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Front image')),
                ('side_image_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Side image')),
                ('back_image_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Back image')),
                ('chest', django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance)),
                ('waist', django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance)),
                ('hip', django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance)),
                ('leg', django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance)),
                ('bicep', django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance)),
                ('bodyweight', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
