# Generated by Django 3.0.7 on 2020-06-07 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200607_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_measure', models.DateField(auto_now_add=True, unique=True)),
                ('front_image_url', models.ImageField(blank=True, null=True, upload_to='entrymeasures/pictures')),
                ('side_image_url', models.ImageField(blank=True, null=True, upload_to='entrymeasures/pictures')),
                ('back_image_url', models.ImageField(blank=True, null=True, upload_to='entrymeasures/pictures')),
                ('chest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('leg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bicep', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bodyweight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
