# Generated by Django 3.0.7 on 2020-06-23 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrymeasures', '0002_auto_20200622_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymeasure',
            name='date_measure',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
