# Generated by Django 3.0.7 on 2020-08-10 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entrymeasures', '0003_auto_20200810_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymeasure',
            name='date_measure',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
