# Generated by Django 3.0.7 on 2020-06-27 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrymeasures', '0004_auto_20200627_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymeasure',
            name='date_measure',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
