# Generated by Django 3.0.7 on 2020-07-10 18:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrymeasures', '0005_auto_20200627_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymeasure',
            name='back_image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Back image'),
        ),
        migrations.AlterField(
            model_name='entrymeasure',
            name='front_image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Front image'),
        ),
        migrations.AlterField(
            model_name='entrymeasure',
            name='side_image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Side image'),
        ),
    ]
